name: "Record test results to build action"
author: "launchableinc"
description: "Launchable action for recording test results to a build"
branding:
  icon: 'circle'
  color: 'gray-dark'
inputs:
  build_name:
    required: true
    description: "The build name to record these tests against."
  python_version:
    required: false
    description: "Python version >= 3.5 <=3.10. Default 3.10"
    default: "3.10"
  report_path:
    required: true
    description: "The test report file path. Default ."
    default: "."
  test_runner:
    required: true
    description: "Test runner name"
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - id: install
      shell: bash
      run: pip install launchable
    - id: verify
      shell: bash
      run: |
        launchable verify
    - id: record_test
      shell: bash
      run: |
          launchable record tests \
            --build ${{ inputs.build_name }} \
            ${{ inputs.test_runner }} \
            ${{ inputs.report_path }}
